### ISSUE TITLE
Tampering detection in an image captured from a tampered document.

### ISSUE THREAD

**Issue by farooq-zaman-82** [qcf-568/DocTamper#48]
Hi, does this model works for use cases whereby a person captures an image of a document using scanner for example, make changes to the document, capture an image of tampered document using smartphone and submit to the system? I tried this model on images with no tampering, captured using smartphone camera but model is showing lot of tampering. Please see the attached image.

![prediction](https://github.com/qcf-568/DocTamper/assets/59040931/5901b9b7-c388-4fda-9b6c-bcef015d2a79)

Any guidance is truly appreciated.

**Comment by qcf-568** [comment]
This model only works for digital tampering, instead of physical tampering where forgery is done before image capturing. The open-source model is only trained with tampered images for demonstration, it's suggested fine-tuning it with authentic samples and edge padded samples for some cases. Moreover, some things should be noted during inference (e.g. resize is not allowed).
