### ISSUE TITLE
About dataset setting for training and inference.

### ISSUE THREAD

**Issue by RobotDouble** [qcf-568/DocTamper#53]
Hi Mr. qcf-568,

Thank you for your contributions to the field of document tampering detection. Your work is great but I am encountering a few issues that I hope you can help clarify:

1) **Training and Inference Approach**: I noticed that you use image patches for both training and inference, rather than resizing original images to 512x512. Typically, tampering detection involves inputting original document images resized to a specific dimension into the detection model. Could you explain the rationale behind this unconventional approach of using image patches?

2) **Performance Discrepancy**: I have successfully reproduced your method on the DocTamper dataset, where it performs excellently. However, when applied to my own dataset, which consists of tampered document images resized to 512x512 (The original image is a high-definition scanned image of the document, with a resolution of approximately `1k+`x`2k+`), the performance drastically declines (all metrics drop to zero). Intriguingly, when I cut these images into patches to create a new 'dataset_patches', your method performs well again. I've noticed that resizing the images tends to blur them and reduce clarity, whereas the image patches maintain their original clarity. Could the clarity of the images be significantly impacting the effectiveness of your method?

**Comment by qcf-568** [comment]
Hello,

The resize function is forbidden, since this method relies on the `block artifacts grids` for tampering localization. When the input image is resized, its `block artifacts grids` will be totally destroyed, so this method does not work in this case. However, by utilizing the `block artifacts grids`, model can gain much more better fine-grained perception ability to detect visually consistent tampering, which is important for tampered text detection in documents. Moreover, by utilizing the `block artifacts grids`, model can gain much more better cross-domain generalization. So, this methods is sacrificing anti-resize for better detection and generalization abilities.

**Comment by ShaoqingHan123** [comment]
@Nomiluks Please refer to L39~L137 https://github.com/qcf-568/DocTamper/blob/main/models/tsroie/infer_sroie.py​

and this colab notebook https://colab.research.google.com/drive/1rWaSKy2Rsy5welyvj6FbzF01o2zv8ips?usp=sharing

**Comment by qcf-568** [comment]
@Nomiluks Please refer to L39~L137 https://github.com/qcf-568/DocTamper/blob/main/models/tsroie/infer_sroie.py​

and this colab notebook https://colab.research.google.com/drive/1rWaSKy2Rsy5welyvj6FbzF01o2zv8ips?usp=sharing
