### ISSUE TITLE
Question about infer on JPEG images and Quant table

### ISSUE THREAD

**Issue by PhmHiu** [qcf-568/DocTamper#56]
Hi, I have concerns about two things:
- Firstly, what is the correct way to infer with the JPEG image. Do I read the dct and quant table from the original jpeg file or I first read it and convert to Y-channel, save that image with 100% quality and read dct, quant table from the saved file?
- Secondly, the model got error when the value in quant table greater than 63 because the model architecture will only embed value of quant table from 0 to 63. Is it an error in the model or we must clip the value of quant table to this range?

Thank you, hope to hear back from you soon

**Comment by PhmHiu** [comment]
Thank you very much. I have another small question, can the model work well with scanned documents, or it only works well with image capture from camera

**Comment by qcf-568** [comment]
This version of DTD mainly works well with image capture from camera, since it relys on block artifact grids to achieve better performance, and the block artifact grids only exist in compressed image. If scaned documents are compressed before tampering (e.g. images in the T-SROIE dataset), this version of DTD can also work well on them.
